/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Persistence.CompraTxtDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Alexandre
 */
public class PesqCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form PesqCompra
     */
    public PesqCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPesqCompra = new javax.swing.JComboBox<>();
        jTextFieldPesqCompra = new javax.swing.JTextField();
        jButtonPesqCompra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesqCompra = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Forma de pesquisa");

        jComboBoxPesqCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "ID da compra", "ID do fornecedor", "Data da compra" }));

        jButtonPesqCompra.setText("Pesquisar");
        jButtonPesqCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesqCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxPesqCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jTextFieldPesqCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPesqCompra)
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPesqCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesqCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesqCompra))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTablePesqCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID da compra", "ID do fornecedor", "Data da compra"
            }
        ));
        jScrollPane1.setViewportView(jTablePesqCompra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesqCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesqCompraActionPerformed
        CompraTxtDao cD = new CompraTxtDao();
        DefaultTableModel dtmCompra = (DefaultTableModel)jTablePesqCompra.getModel();
        if(jComboBoxPesqCompra.getSelectedItem().toString().equals("ID da compra")){
          if(cD.buscarPorID(Integer.parseInt(jTextFieldPesqCompra.getText())) != null){
           Object[] Vdados = {cD.buscarPorID(Integer.parseInt(jTextFieldPesqCompra.getText())).getId(),cD.buscarPorID(Integer.parseInt(jTextFieldPesqCompra.getText())).getData(),cD.buscarPorID(Integer.parseInt(jTextFieldPesqCompra.getText())).getIdFornecedor()};
            dtmCompra.addRow(Vdados);
          }else{
                JOptionPane.showMessageDialog(null, "Não encontrado");
          }
      
        }else if(jComboBoxPesqCompra.getSelectedItem().toString().equals("ID do fornecedor")){
            if(cD.buscarPorID(Integer.parseInt(jTextFieldPesqCompra.getText())) != null){
            String[] Vdados = {Integer.toString(cD.buscarPorID(Integer.parseInt(jTextFieldPesqCompra.getText())).getId()),cD.buscarPorID(Integer.parseInt(jTextFieldPesqCompra.getText())).getData(),Integer.toString(cD.buscarPorID(Integer.parseInt(jTextFieldPesqCompra.getText())).getIdFornecedor())};
            dtmCompra.addRow(Vdados);
            }else{
                JOptionPane.showMessageDialog(null, "Não encontrado");
            }
                
        }else if(jComboBoxPesqCompra.getSelectedItem().toString().equals("Data da compra")){
            if(cD.buscarPorData(jTextFieldPesqCompra.getText()) != null){
                String[] Vdados = new String[3];
                for(int i = 0;i <= cD.buscarPorData(jTextFieldPesqCompra.getText()).size()-1;i++){
                    Vdados[0] = Integer.toString(cD.buscarPorData(jTextFieldPesqCompra.getText()).get(i).getId());
                    Vdados[1] = cD.buscarPorData(jTextFieldPesqCompra.getText()).get(i).getData();
                   Vdados[2] = Integer.toString(cD.buscarPorData(jTextFieldPesqCompra.getText()).get(i).getIdFornecedor());
                    dtmCompra.addRow(Vdados);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Não encontrado");
            }
         }
        
    }//GEN-LAST:event_jButtonPesqCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesqCompra;
    private javax.swing.JComboBox<String> jComboBoxPesqCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesqCompra;
    private javax.swing.JTextField jTextFieldPesqCompra;
    // End of variables declaration//GEN-END:variables
}
